version: '3.9'

services:
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=dripchip
      - POSTGRES_PASSWORD=FvXVPa5Nt9rkU7dZ
  
  webapi:
    build:
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings:DefaultConnection=Host=database;Port=5432;Database=animal-chipization;Username=dripchip;Password=FvXVPa5Nt9rkU7dZ
  
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:80
      STAGE: all