version: '3.9'

services:
  database:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=dripchip
      - POSTGRES_PASSWORD=FvXVPa5Nt9rkU7dZ
  
  webapi:
    build:
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=animal-chipization
      - POSTGRES_USER=dripchip
      - POSTGRES_PASSWORD=FvXVPa5Nt9rkU7dZ
  
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:8080/api
      STAGE: all